#!/bin/bash
# remap the ethernet ports.
#
### BEGIN INIT INFO
# Provides:          ethmap
# Required-Start:    $syslog $time
# Required-Stop:     $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Author: Leif Sawyer <lsawyer@gci.com>
# Short-Description: remaps ethernet interfaces by order of mac address
# Description:       This is the start/stop wrapper for map-ifs which
#                       remaps ethernet interface names via udev rules.
### END INIT INFO

remap=$(/usr/local/bin/map-ifs|tail -1)

if [ -n "$remap" ];
then
   mount -o remount,rw -n /
   /usr/local/bin/map-ifs > /etc/udev/rules.d/70-persistent-net.rules
   PHY="$(grep eth0 /etc/udev/rules.d/70-persistent-net.rules | egrep -o '\"[0-9]{2}:.*' | cut -f 2 -d\" | cut -f 4- -d: | sed 's/://g' )"
   HN="l2fw-${PHY}"
   echo ${HN} > /etc/hostname
   sed -i "s/127.0.1.1.*/127.0.1.1 ${HN}.gci.net ${HN}/g" /etc/hosts
   mount -o remount,ro -n /
   echo "Rebooting for eth name changes to take effect"
   reboot
fi
